version: "3"
services:
  client:
    build: .
    command: yarn start
    ports:
      - 4000:4000
    environment:
      - PORT=4000
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules


