AllCops:
  TargetRubyVersion: 2.4

Documentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*

Metrics/LineLength:
  Enabled: true
  Exclude:
    - spec/**/*

Style/FrozenStringLiteralComment:
  Enabled: false

Style/AsciiComments:
  Enabled: false
