version: "3"
services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      - RAILS_ENV=test
    links:
      - postgres
    env_file:
      - .env.development

  # Need to replace with RDS.
  postgres:
    image: postgres:9.6
    volumes:
      - pg_data:/var/lib/postgresql/data
  client:
    build: ./client
    volumes:
      - ./client/build:/usr/src/app/build
    env_file:
      - .env.development
volumes:
  pg_data:
