version: "3"
services:
  web:
    build:
      context: .
      dockerfile: config/docker/development/Dockerfile
    command: bundle exec rails s -b 0.0.0.0
    ports:
      - 80:80
    volumes:
      - ./api:/home/app/webapp
      - bundle:/usr/local/bundle
    environment:
      - RAILS_ENV=development
      - PORT=80
    links:
      - postgres
  postgres:
    image: postgres:latest
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  bundle:
  pg_data:


