version: "3"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    links:
      - client
      - api
  client:
    build: ./client
    command: yarn start
    ports:
      - 4000:4000
    environment:
      - PORT=4000
    volumes:
      - ./client:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    env_file:
      - .env.development
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    command: bundle exec rails s -p 5000 -b 0.0.0.0
    environment:
      - PORT=5000
    ports:
      - 5000:5000
    volumes:
      - ./api:/home/app/webapp
      - ./STAGING:/home/app/webapp/STAGING
      - bundle:/usr/local/bundle
    links:
      - postgres
    env_file:
      - .env.development
  postgres:
    image: postgres:9.6
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  bundle:
  pg_data:
  node_modules:

