version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    restart: always
    ports:
      - 80:80
    links:
      - api
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    command: bundle exec rails s -b 0.0.0.0
    restart: always
    environment:
      - RAILS_ENV=production
      - PORT=5000
      - RAILS_LOG_TO_STDOUT=true
    env_file:
      - .env.production
    volumes:
      - ./api/log:/home/app/webapp/log

  client:
    build: ./client
    command: echo 'not running in production'
    ports:
      - 4000:4000
    environment:
      - PORT=4000
    volumes:
      - ./client/build:/usr/src/app/build
    env_file:
      - .env.production


