# This is used for making client build with correct
# environment variables
version: "3"
services:
  client:
    build: ./client
    command: yarn start
    ports:
      - 4000:4000
    environment:
      - PORT=4000
    volumes:
      - ./client/build:/usr/src/app/build
      - node_modules:/usr/src/app/node_modules
    env_file: .env.production
volumes:
  node_modules:

