version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 5000 -b 0.0.0.0
    environment:
      - RAILS_ENV=development
      - PORT=5000
      - DB_USERNAME=postgres
      - DB_HOSTNAME=postgres

    ports:
      - 5000:5000
    volumes:
      - ./api:/usr/src/api
      - /usr/src/api/tmp
      - /usr/local/bundle
    environment:
      - BUNDLE_PATH=/usr/local/bundle
    links:
      - postgres
  postgres:
    image: postgres:latest
    volumes:
    - /var/lib/postgresql/data


